name: Update Quickbase EDL IPs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-edl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python
        uses: actions/setup-python@0d103c312664f22f79025e933f7b82f0c793a382
        with:
          python-version: '3.10'

      - name: Run Resolution Script
        run: python update_ips.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@8621434c4dcb70ede8519d0e2e92cfa76e932ec3
        with:
          commit_message: "Auto-update Quickbase EDL IP list [skip ci]"
          file_pattern: "quickbase_ips.txt"
